### ISSUE TITLE
Cache limit quotas

### ISSUE THREAD

**Issue by Trojan295** [nokia/consumer-rate-limiting#1]
Currently for every call the limit quotas are queried from the datastore. It would be a good improvement to cache this for ex. 1 hour, so the requests get processed faster.

**Comment by unsignedint** [comment]
I would like to take this, if I may.

**Comment by Trojan295** [comment]
Sure, go on :)

**Comment by unsignedint** [comment]
A question: the current schemas refer to `api_id` yet in the controller we have something like following:
```lua
    local quota = self.quota_gateway.get(consumer.id, api.name)  -- <= note "api.name"
```
See https://github.com/nokia/consumer-rate-limiting/blob/master/kong/plugins/consumer-rate-limiting/controller.lua#L17

So, we are actually relying/matching the API *name* and not ID. I feel this could be confusing, and I just want to confirm that actually we want to use the *name* for this plugin. (And we just accept the fact the database field is written as `_id`)

Hope that makes sense.

**Comment by unsignedint** [comment]
I have ignored the question about **id** vs **name** and made an initial PR. Suggestions for improvement welcome :)

**Comment by Trojan295** [comment]
Yes, you are right, the `api_id` refers to the API name. In fact, it's enough fo the `api_id` to be a substring of the API name.
The genesis of it were our internal use cases, but I consider making it more generic to support also id's.
