### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by Trojan295** [nokia/consumer-rate-limiting#6]
This repository has now Travis CI tests. I run them on my fork and it's working fine (https://travis-ci.org/Trojan295/consumer-rate-limiting). The README.md already points to nokia/consumer-rate-limiting on Travis.

@CsatariGergely, could you enable Travis CI for this repository (https://travis-ci.org/nokia/consumer-rate-limiting)?

**Comment by CsatariGergely** [comment]
https://travis-ci.org/nokia/consumer-rate-limiting is activated now.
